[workflow] auto cancel

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -35,8 +35,8 @@ jobs:
       - name: Check if tag is valid
         run: |
           if [[ ! "${{ github.ref_name }}" =~ ^refs/tags/v.* ]]; then
-            echo "This workflow must only run for a tag and not a branch."
-            exit 1
+            echo "Auto Cancel: The event was triggered by a branch push or an invalid tag."
+            exit 78 
           fi
 
       - name: Checkout code
